[CI] Add i18n Parser Check
HyperPlay-Gaming/hyperplay-desktop-client pull request #1078
Opened 2024-09-19 19:23 UTC by flavioislima

<--- Put the description here --->

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

2024-09-19 19:26 UTC, flavioislima commented
For testing, just check the first commit, it failed since there were some keys that were added but we forgot to update.
The second commit contains the keys and then the check passes.

2024-09-19 19:48 UTC, BrettCleary requested changes

2024-09-19 19:48 UTC, BrettCleary commented on .github/workflows/translations_parser.yml
can we use our reusable workflows so this is easier to maintain?

2024-09-19 19:48 UTC, BrettCleary commented on .github/workflows/translations_parser.yml
here is an example https://github.com/HyperPlay-Gaming/hyperplay-ui/blob/main/.github/workflows/lint.yml

2024-09-20 10:47 UTC, flavioislima commented on .github/workflows/translations_parser.yml
Tried but for some reason the parser fails everytime even though no keys were added to it.

2024-09-20 18:38 UTC, BrettCleary commented on .github/workflows/translations_parser.yml
I think it needs to be `checkout_recursive: false` because if it is true you need to pass the `pat` secret. We don't need recursive checkout any more though since there are no submodules

2024-09-20 18:39 UTC, BrettCleary commented on .github/workflows/translations_parser.yml
oh I see you tried that. taking a look at the latest

2024-09-26 19:11 UTC, flavioislima commented on .github/workflows/translations_parser.yml
working now

2024-09-26 19:13 UTC, BrettCleary approved these changes
LGTM!

2024-09-30 20:07 UTC, eliobricenov approved these changes

2024-09-30 20:30 UTC, merged