Analitycs consent modal update
HyperPlay-Gaming/hyperplay-desktop-client pull request #1171
Opened 2024-11-26 23:35 UTC by biliesilva

<--- Update Analytics Consent modal / Add new card when Privacy is updated --->

---
These are the updates: 

Copy and Style updates
![image](https://github.com/user-attachments/assets/cda4e476-bf4e-44cf-94e3-e805c8d41e39)

New card when we have the privacy policy update
![image](https://github.com/user-attachments/assets/af43f912-8080-4191-b07b-eaf2ce216901)

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

2024-11-27 15:51 UTC, jiyuu-jin approved these changes
New styles look 🔥

2024-12-03 07:57 UTC, BrettCleary requested changes
looks great! requested a couple small changes

2024-12-03 07:57 UTC, BrettCleary commented on src/frontend/screens/Onboarding/welcome/index.tsx
isn't this handled on https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/1163

2024-12-03 07:57 UTC, BrettCleary commented on src/frontend/screens/Onboarding/analytics/index.tsx
looks good but could we change the component name to `ModalUpdatedPrivacyPolicy` or something like that?

2024-12-03 20:44 UTC, biliesilva commented on src/frontend/screens/Onboarding/welcome/index.tsx
yes, I will fix this later today, ty!

2024-12-03 23:48 UTC, eliobricenov approved these changes
lgtm

2024-12-04 12:15 UTC, biliesilva commented on src/frontend/screens/Onboarding/analytics/AnalyticsV2/index.tsx
> +function AnalyticsV2() {
The other is for browser users (users who land the first time on our store through the website and haven't accepted the privacy policy); this one here is to share a new update in the privacy policy.

2024-12-05 21:07 UTC, BrettCleary requested changes
pr is close. just some small naming change requests

2024-12-05 21:07 UTC, BrettCleary commented on src/frontend/App.tsx
> +import CardPrivacyPolicy from './screens/Onboarding/analytics/CardPrivacyPolicy'
I believe this is because the folder is named `cardPrivacyPolicy`. Can we uppercase it since it is a react component to be `CardPrivacyPolicy`?

2024-12-05 21:07 UTC, BrettCleary commented on src/frontend/assets/hyperplay/Consent Modal/check-circle.svg
can we change this folder name to `consent-modal` to match the other frontend assets naming conventions?

2024-12-06 00:04 UTC, nyghtstalker approved these changes
The new consent modal looks great!

![image](https://github.com/user-attachments/assets/b7c63b66-655c-4b96-b9d4-3881416e1a7c)

2024-12-06 00:23 UTC, BrettCleary commented
you may need to run `yarn i18n` again @biliesilva

2024-12-06 00:24 UTC, BrettCleary approved these changes
LGTM! Great job on this one 🥳 🔥 🚒

2024-12-06 22:11 UTC, merged