[OTHER]: Pull Heroic latest fixes and features
HyperPlay-Gaming/hyperplay-desktop-client pull request #295
Opened 2023-05-02 09:21 UTC by flavioislima

Got some fixes that Heroic had recently.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

2023-05-05 08:04 UTC, flavioislima commented
@stormcakes There are a few things to test on this one:
- On the Add Game Dialog, there is a bug on the current release that the Finish button is not clickable if an image for the game was not found. This should be fixed on this PR.
- On the Epic Login page, the captcha was not working and was always returning an error with an invalid response. Should be fixed as well.
- Sideloaded games (added on the Add Game dialog), did not have the play status working correctly. They changed to Playing but never got out of it even after the game got close.
- And the latest thing to test is the new feature of searching for a game on the search bar and clicking on it should take you to the game page.

Other than that are minor changes that do not need to be deeply tested.

2023-05-05 08:14 UTC, flavioislima commented
Added one last fix to the Add Game dialog:
- On the current release all platforms are showing on all OSes, that is wrong since you cannot run a macOS app on linux and vice-versa. This should be fixed now.

2023-05-10 03:13 UTC, stormcakes commented
On windows OS when sideloading a game (I used League of Legends) and playing the game, while the game is open the Play button and "Playing" text goes away and the user can click "Play" again. @flavioislima

2023-05-10 03:20 UTC, stormcakes commented
Verified the following so far:

- On the Add Game Dialog, there is a bug on the current release that the Finish button is not clickable if an image for the game was not found. This should be fixed on this PR.
- And the latest thing to test is the new feature of searching for a game on the search bar and clicking on it should take you to the game page.

Issues found with: 
-Sideloaded games (added on the Add Game dialog), did not have the play status working correctly. They changed to Playing but never got out of it even after the game got close. [I can create a separate bug if needed.]

WIP:
- On the Epic Login page, the captcha was not working and was always returning an error with an invalid response. Should be fixed as well.
- On the current release all platforms are showing on all OSes, that is wrong since you cannot run a macOS app on linux and vice-versa. This should be fixed now.

2023-05-10 03:23 UTC, stormcakes commented
All testing so far has been performed on Windows - will expand to MacOS (both M1 and Intel) soon and then move to Linux.

2023-05-11 01:36 UTC, BrettCleary requested changes

2023-05-11 01:44 UTC, BrettCleary commented
> Sideloaded games (added on the Add Game dialog), did not have the play status working correctly. They changed to Playing but never got out of it even after the game got close. [I can create a separate bug if needed.]

This is a separate issue. Basically sometimes when you sideload a game you launch an exe that launches another exe but the play status/stop button only affects/tracks the first exe

2023-05-11 02:01 UTC, BrettCleary commented
> On the Add Game Dialog, there is a bug on the current release that the Finish button is not clickable if an image for the game was not found. This should be fixed on this PR.
> On the Epic Login page, the captcha was not working and was always returning an error with an invalid response. Should be fixed as well.
> Sideloaded games (added on the Add Game dialog), did not have the play status working correctly. They changed to Playing but never got out of it even after the game got close.
> And the latest thing to test is the new feature of searching for a game on the search bar and clicking on it should take you to the game page.

Tested and these are all working

2023-05-11 02:04 UTC, stormcakes commented
I can make a seperate ticket for the bug of sideloading but everything else looks good to me. I didnt run into the captcha verification but i was able to auth :)

2023-05-11 02:05 UTC, stormcakes approved these changes
From the test pov besides the sideloading bug 
(which will be written up seperately) - everything is working fine so i'll go ahead and approve :)

2023-05-11 09:12 UTC, flavioislima commented on src/backend/storeManagers/sideload/games.ts
> +    }
done

2023-05-11 09:12 UTC, flavioislima commented on src/backend/storeManagers/sideload/library.ts
> +  art_square = 'fallback',
done

2023-05-11 09:12 UTC, flavioislima commented on src/frontend/helpers/gamepad.ts
> +    console.log(e)
yes, done

2023-05-11 20:30 UTC, BrettCleary approved these changes
LGTM

2023-05-11 23:00 UTC, merged