[CI] Windows Release and Signing
HyperPlay-Gaming/hyperplay-desktop-client pull request #505
Opened 2023-09-01 12:39 UTC by flavioislima

<--- Put the description here --->

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

2023-09-05 23:22 UTC, BrettCleary requested changes
GHA looks good. All the builds are failing now though. I think it's due to the yarn.lock updates so maybe we should revert those

2023-09-05 23:22 UTC, BrettCleary commented on yarn.lock
This is a lot of updates. Is this from `yarn upgrade`? 

Looks like these dependency updates are causing the builds to fail too. 

Maybe we should revert to the previous lockfile and handle these updates on a separate branch

2023-09-06 10:28 UTC, flavioislima commented on yarn.lock
Fixed

2023-09-06 22:44 UTC, BrettCleary approved these changes
LGTM

2023-09-07 20:06 UTC, eliobricenov approved these changes

2023-09-11 09:21 UTC, merged