[UX] Delete HyperPlay app config folder on reset
HyperPlay-Gaming/hyperplay-desktop-client pull request #751
Opened 2024-02-22 20:51 UTC by BrettCleary

# Summary
To reset the entirety of HyperPlay, including the MetaMask extension, you will now just need to click this "Reset HyperPlay" button

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/27568879/bf74949a-0a10-4ee7-97c1-b421b84c506f)

Previously, it would only delete the `appFolder/hyperplay/GamesConfig` and `appFolder/hyperplay/config.json` files
 
---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

2024-02-22 20:52 UTC, red-game-dev approved these changes
That was super quick! LGTM, amazing work!

2024-02-22 20:53 UTC, eliobricenov approved these changes

2024-02-22 23:31 UTC, nyghtstalker commented
1. After clicking the reset button I am getting an error in the terminal and HP reopens with a blank, white screen.

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/aa2befc3-bf63-4906-bb1d-96a205846168)

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/d0fa3728-466f-4cb2-9566-94f1ae025550)

2024-02-23 00:39 UTC, flavioislima commented
Shouldn't we communicate to the user that it will lose all their games and all installed ones will appear as uninstalled?

I think that is the biggest issue.
Not sure if it's a good idea since the person might have tons of installed games and will need to import them one by one.
Also the compatibility layers will be deleted as well

2024-02-23 00:45 UTC, nyghtstalker commented
> Shouldn't we communicate to the user that it will lose all their games and all installed ones will appear as uninstalled?
> 
> I think that is the biggest issue. Not sure if it's a good idea since the person might have tons of installed games and will need to import them one by one. Also the compatibility layers will be deleted as well

@flavioislima this message appears after clicking reset and must click YES to continue with the reset.

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/aa52f38f-8eee-45c6-8a70-e745215df446)

2024-02-23 01:06 UTC, BrettCleary commented
> Shouldn't we communicate to the user that it will lose all their games and all installed ones will appear as uninstalled?
> 
> I think that is the biggest issue. Not sure if it's a good idea since the person might have tons of installed games and will need to import them one by one. Also the compatibility layers will be deleted as well

it is a reset button. I think it should reset everything. if we want to just reset configs, we should have a separate reset configs button imo

We have a modal being worked on that communicates this better as well

2024-02-23 01:09 UTC, BrettCleary commented
This one is being kicked to the next release due to issues with Windows EPERM errors and to allow for more discussion

2024-02-23 03:31 UTC, BrettCleary commented
deprioritizing this one as https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/752 handles the critical need. 

will leave this one open to discuss what we want the reset hyperplay button to do tho

2024-02-23 13:02 UTC, flavioislima commented
> > Shouldn't we communicate to the user that it will lose all their games and all installed ones will appear as uninstalled?
> > I think that is the biggest issue. Not sure if it's a good idea since the person might have tons of installed games and will need to import them one by one. Also the compatibility layers will be deleted as well
> 
> @flavioislima this message appears after clicking reset and must click YES to continue with the reset.
> 
> ![image](https://private-user-images.githubusercontent.com/82125535/307196333-aa52f38f-8eee-45c6-8a70-e745215df446.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2OTMzNzYsIm5iZiI6MTcwODY5MzA3NiwicGF0aCI6Ii84MjEyNTUzNS8zMDcxOTYzMzMtYWE1MmYzOGYtOGVlZS00NWM2LThhNzAtZTc0NTIxNWRmNDQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDEyNTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5YWRmMzRmZmExYzA3MmQzMTJkNDE2MzI1ZGMxMTM2YmRlNjA1MDE3MmNmOTJhMzkwNzZjMGYyZmFiNDBiMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9JeUpHJfiKEbvbxgCVqBel6LRu2aRXhONzdz8QiacPE)

This message says the otherwise, that you won't lose your games.
But deleting the hyperplay folder now will delete all your configurations and also remove all your games.
The worst part is that it won't uninstlal the games, so the downloaded games will be there but you will need to import them one by one. I imagine a lot of people won't know how to do that and just download the game again.

Even if they know how to import them, imagine if the person has 10, 20 games downloaded in different partitions, it will be a strugle for them to manually do that.

We are also talking about GOG and Epic games, sideloaded ones as well.

@BrettCleary Another idea is to rename the current button to: 'Reset App Settings' and add a third one that will drop this atomic bomb, but showing a warning to the user saying that all downloaded games will need to be imported manually afterwards. That is a better solution imo since the idea for this button is only to reset the default settings.

2024-02-23 13:07 UTC, flavioislima requested changes
A third way would be better like I said above, otherwise will be pretty confusing to users and we will lose the ability to only reset the settings in case the person does not need to delete other things like the wallet.

2024-02-26 23:44 UTC, BrettCleary commented
closing this as it was handled on another branch

2024-02-26 23:44 UTC, closed without merging