Feat: Advanced Options
HyperPlay-Gaming/hyperplay-desktop-client pull request #782
Opened 2024-03-04 19:22 UTC by red-game-dev

Ticket: https://github.com/orgs/HyperPlay-Gaming/projects/1/views/1?pane=issue&itemId=54670406

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

2024-03-04 19:24 UTC, red-game-dev commented
At some point on this, I was thinking of moving it to the `@hyperplay/ui` component package, but this could be enhanced later because we wouldn't be required to edit this repository other than upgrade the package for these instances.

2024-03-04 20:53 UTC, BrettCleary commented
@red-game-dev I think we should change the text to "Show Advanced Settings" if collapsed and "Hide Advanced Settings" if expanded

2024-03-04 20:55 UTC, red-game-dev commented
> @red-game-dev I think we should change the text to "Show Advanced Settings" if collapsed and "Hide Advanced Settings" if expanded

Yup make sense, on it 🙏

2024-03-04 20:58 UTC, BrettCleary requested changes
Requesting changes for my comment above for the button text

2024-03-04 20:58 UTC, BrettCleary commented on src/frontend/screens/Onboarding/walletSelection/screens/import/components/ImportAndCreateOptions/index.tsx
> +        {isOpenAdvancedOptions && (
can we make this a ternary https://medium.com/geekculture/stop-using-for-conditional-rendering-in-react-a0f7b96200f8

2024-03-06 22:54 UTC, BrettCleary commented
were we waiting on designs for this one @red-game-dev ?

2024-03-07 18:10 UTC, red-game-dev commented
> were we waiting on designs for this one @red-game-dev ?

Ye, but  @iamdavid0091 replied with the changes needs to be applied, https://github.com/HyperPlay-Gaming/product-management/issues/188#issuecomment-1981607149

2024-03-11 19:41 UTC, iamdavid0091 commented
@red-game-dev here is the [Figma link](https://www.figma.com/file/GKPELZxk551oVC3EDLgEDA/Current-Design?type=design&node-id=9848%3A2021&mode=design&t=fHJ81AIIx72cgk6P-1) you requested.

2024-03-18 22:32 UTC, BrettCleary commented
@red-game-dev 

1. The "Chrome" text should be neutral-400
2. The top and bottom padding on the browser import button should be larger
3. There is too much spacing between the metamask icons and the text below them for "Import Using Secret Recovery Phrase" and "Create New Extension Wallet"
4. The browser icon is 24x24 px on the design but 32x32 px on this branch

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/27568879/28720274-6e25-4c15-9947-114812f82d4f)

2024-03-19 19:15 UTC, red-game-dev commented
> @red-game-dev comparing this to https://www.figma.com/file/GKPELZxk551oVC3EDLgEDA/Current-Design?type=design&node-id=9848-73492&mode=design&t=KeWWWRtJVeKKwsxy-4
> 
> 1. The "Chrome" text should be neutral-400
> 2. The top and bottom padding on the browser import button should be larger
> 3. There is too much spacing between the metamask icons and the text below them for "Import Using Secret Recovery Phrase" and "Create New Extension Wallet"
> 4. The browser icon is 24x24 px on the design but 32x32 px on this branch
> 
> ![image](https://private-user-images.githubusercontent.com/27568879/313853669-28720274-6e25-4c15-9947-114812f82d4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NzU5OTEsIm5iZiI6MTcxMDg3NTY5MSwicGF0aCI6Ii8yNzU2ODg3OS8zMTM4NTM2NjktMjg3MjAyNzQtNmUyNS00YzE1LTk5NDctMTE0ODEyZjgyZDRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDE5MTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YTAyMDVlOTViYzQwOTVjNmI3NzUzZWEyYzIyOTRlMzk5MTI2MzJmMzgxODU2MDVlZDY0NTJjZWEzYWQ2MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C5kvvHv0HTDzrGxriBFEMZtO33jNxufWy1Cn6ALWHTE)

Sorted, cheers for the helpful list of issues 🙏 🙌

2024-03-20 19:57 UTC, BrettCleary approved these changes
LGTM

2024-03-25 14:07 UTC, eliobricenov approved these changes

2024-03-26 17:26 UTC, merged