Translations update from Hosted Weblate
HyperPlay-Gaming/hyperplay-desktop-client pull request #846
Opened 2024-04-08 09:16 UTC by weblate

Translations update from [Hosted Weblate](https://hosted.weblate.org) for [HyperPlay Client/Login Page](https://hosted.weblate.org/projects/hyperplay-client/login-page/).

It also includes following components:

* [HyperPlay Client/Globals](https://hosted.weblate.org/projects/hyperplay-client/globals/)

* [HyperPlay Client/GamePage](https://hosted.weblate.org/projects/hyperplay-client/gamepage/)

Current translation status:

![Weblate translation status](https://hosted.weblate.org/widget/hyperplay-client/login-page/horizontal-auto.svg)

2024-04-17 18:27 UTC, flavioislima approved these changes

2024-04-18 14:13 UTC, eliobricenov requested changes

2024-04-18 14:13 UTC, eliobricenov commented on public/locales/es/translation.json
> +                "message": "La instalación de Ubisoft Connect en el prefijo del juego ha fallado. Consulte nuestra página wiki en https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/How
this is a mistake, maunally is not a spanish word

2024-04-18 14:13 UTC, eliobricenov commented on public/locales/es/translation.json
> +        "ETA": "Hora prevista"
I'd argue the prev one was better

2024-04-18 14:15 UTC, eliobricenov commented
@flavioislima how do we handle incorrect translations? second one I commented is fine to leave, but the first one is a mistake

2024-04-18 14:35 UTC, flavioislima commented
> @flavioislima how do we handle incorrect translations? second one I commented is fine to leave, but the first one is a mistake

Even in Spanish from Spain they are wrong?
The correct way would be you creating an account in weblate and fixing there. Or fix it on another PR after merging this one.

2024-04-18 19:22 UTC, flavioislima commented
@eliobricenov fixed it on weblate. Check now.

2024-04-22 15:49 UTC, eliobricenov approved these changes

2024-04-23 10:06 UTC, merged